### ISSUE TITLE
blockNumber卡住的问题

### ISSUE THREAD

**Issue by zyd82** [caivega/ipfslib#12]
经常碰到链在出块，但是在7545和9545上blockNumber卡住的问题，需要解决。

`zyds-mbp:node.js.script zyd$ curl -X POST --data '{"jsonrpc":"2.0","method":"jt_blockNumber","params":[],"id":1}' http://139.198.191.254:7545/v1/jsonrpc
{"id":1,"jsonrpc":"2.0","result":105499,"status":"success"}`

`zyds-mbp:node.js.script zyd$ curl -X POST --data '{"jsonrpc":"2.0","method":"jt_blockNumber","params":[],"id":1}' http://139.198.191.254:9545/v1/jsonrpc
{"id":1,"jsonrpc":"2.0","result":105499,"status":"success"}`

**Comment by caivega** [comment]
出问题的那台机器有公网IP，所以时间经常更新，而另外四台是内网机器，没有公网IP，时间一直没更新，导致四台内网机器时间之间的差别很小，四个共识的很好，一直没卡过，刚才发现这个问题，手动通过时间服务器进行同步，接下来观察下运行情况

**Comment by zyd82** [comment]
很久没碰到过了。
