### ISSUE TITLE
[enhancement] - issue token，name（不是symbol）是否可以重名？name长度是否有限制？

### ISSUE THREAD

**Issue by foreso-GitHub** [caivega/ipfslib#133]
issue token，name（不是symbol）是否可以重名？name长度是否有限制？

目前的版本（'20201130': 'v0.5.3-dev'）是允许重名，而且name长度很长（超过60）也是可以 的。

**Comment by foreso-GitHub** [comment]
结论：
1. name允许重复。
2. name长度最多256byte。

**Comment by caivega** [comment]
已经修复，下一个版本验证

另外，issue coin与issue token的name（名称）, 建议后续我们都按这个要求来

**Comment by foreso-GitHub** [comment]
版本：20201205-v0.5.3-dev已经修复。
