### ISSUE TITLE
S3- jt_version，带无效参数，比如"123"、"abc"等，没有查询失败，返回相应的提示信息

### ISSUE THREAD

**Issue by foreso-GitHub** [caivega/ipfslib#166]
jt_version，带无效参数，比如"123"、"abc"等，没有查询失败，返回相应的提示信息。
注意：如果参数是空字符串“”，查询应该成功，等同于没有参数，[FCJT_version_000010](../wiki/_TestCase_FCJT_version/#FCJT_version_000010)，这点目前是正确的。

版本：v0.5.3-dev-20210103-bcc6a93d716c6b4916bf52f55df8fb591ab54965

TestCase: [FCJT_version_000030](../wiki/_TestCase_FCJT_version/#FCJT_version_000030)

```
{
    "jsonrpc": "2.0",
    "method": "jt_version",
    "params": ["123"],
    "id": 1
}

{
    "id": 1,
    "jsonrpc": "2.0",
    "result": "v0.5.3-dev-20210103-bcc6a93d716c6b4916bf52f55df8fb591ab54965"
}
```

**Comment by caivega** [comment]
已经修复，下一个build验证

**Comment by foreso-GitHub** [comment]
在版本v0.5.3-dev-20210111-04c8f9a27b4f9ae2e0f7a74c592a900f7d5d8575中验证，已经修复。
