### ISSUE TITLE
S4 - jt_createWallet：参数相关的几个问题

### ISSUE THREAD

**Issue by zyd82** [caivega/ipfslib#171]
测试版本：v0.5.3-dev-20210111-04c8f9a27b4f9ae2e0f7a74c592a900f7d5d8575
用例编号：FCJT_createWallet_000050

问题一：无效的参数["asdfdsa"]，返回的错误信息"Can't add an already created account."不准确，可以改为“Invalid parameter.”或者“Parameter needs to be: ECDSA, ED25519, or SM2.”
```
{
    "jsonrpc": "2.0",
    "method": "jt_createWallet",
    "params": ["asdfdsa"],
    "id": 1
}
```
```
{
    "error": {
        "description": "Can't add an already created account.",
        "information": "unknown key type"
    },
    "id": 1,
    "jsonrpc": "2.0",
    "status": -191,
    "type": "tefCREATED"
}
```

问题二：参数如果不加[]，不论参数内容是啥，都能成功创建钱包，这里是否考虑如果不加[]的参数应该直接返回参数格式不对的错误？
```
{
    "jsonrpc": "2.0",
    "method": "jt_createWallet",
    "params": "asdfdsa",
    "id": 1
}
```
```
{
    "id": 1,
    "jsonrpc": "2.0",
    "result": [
        {
            "address": "jBp4JiiXd729Dwiu2sce83Qr38BU8Yv8aT",
            "secret": "sskwBpb2Q5VPAsS6u16hzhYBLj4UL",
            "type": "ECDSA"
        }
    ]
}
```

**Comment by caivega** [comment]
已经修复，1.显示bad parameter, 2. 显示invalid parameter

已经修复，见下一个build

**Comment by zyd82** [comment]
@caivega jt_createAccount也碰到了上述的问题一，可以一并修改掉。
```
{
    "jsonrpc": "2.0",
    "method": "jt_createAccount",
    "params": [
        "alhfieufsdiahjsdsdsbjsdhfkahsdjsdfjdalhfieufsdiahjsdsalhfieufsdiahjsdsdsbjsdhfkahsdjsdfjdalhfieufsdiahjsds",
        "ed25519s"
    ],
    "id": 1
}
```
```
{
    "error": {
        "description": "Can't add an already created account.",
        "information": "unknown key type"
    },
    "id": 1,
    "jsonrpc": "2.0",
    "status": -191,
    "type": "tefCREATED"
}
```

**Comment by caivega** [comment]
> @caivega jt_createAccount也碰到了上述的问题一，可以一并修改掉。
> 
> ```
> 
> {
> 
>     "jsonrpc": "2.0",
> 
>     "method": "jt_createAccount",
> 
>     "params": [
> 
>         "alhfieufsdiahjsdsdsbjsdhfkahsdjsdfjdalhfieufsdiahjsdsalhfieufsdiahjsdsdsbjsdhfkahsdjsdfjdalhfieufsdiahjsds",
> 
>         "ed25519s"
> 
>     ],
> 
>     "id": 1
> 
> }
> 
> ```
> 
> ```
> 
> {
> 
>     "error": {
> 
>         "description": "Can't add an already created account.",
> 
>         "information": "unknown key type"
> 
>     },
> 
>     "id": 1,
> 
>     "jsonrpc": "2.0",
> 
>     "status": -191,
> 
>     "type": "tefCREATED"
> 
> }
> 
> ```

已一块修掉了 第二错误 所有API相关的都修复掉了

**Comment by zyd82** [comment]
v0.5.3-dev-20210113-5aa567d27f68102434021e72cbd0bad2349ae99e版本上验证通过。
