### ISSUE TITLE
S3 - jt_listSubscribe，参数不同，返回结果的格式也不同

### ISSUE THREAD

**Issue by foreso-GitHub** [caivega/ipfslib#180]
jt_listSubscribe，参数不同，返回结果的格式也不同，应该统一。
版本：v0.5.4-dev-20210202-95e57512b464d7595068a4dda3e2fe1cfae85d1b
TestCase：[FCJT_listSubscribe_000010](https://github.com/caivega/ipfslib/wiki/_TestCase_FCJT_listSubscribe)

不带参数，返回的第一层result里面没有第二层result
```
{"jsonrpc":"2.0","id":7,"method":"jt_listSubscribe","params":[]}
{
	"id": 7,
	"jsonrpc": "2.0",
	"result": [
		"block",
		"tx",
		"token TSC_2,TSC_3/jHb9CJAWyB4jr91VRWn96DkukG4bwdtyTh",
		"account jHtSHUzSWPgpz9GkkgnPQDbHgRoGMAFUZm,jU6naURtttsbGqWsye6Zag3FfC9hX48nMX"
	],
	"outputIndex": 10
}
```

带参数，返回的第一层result里面有第二层result
```
{"jsonrpc":"2.0","id":10,"method":"jt_listSubscribe","params":["block"]}		
{
	"id": 10,
	"jsonrpc": "2.0",
	"result": [
		{
			"result": "block"
		}
	],
	"outputIndex": 1
}
```

建议统一都带第2层result。

**Comment by caivega** [comment]
done, 下一个build验证

**Comment by foreso-GitHub** [comment]
在版本v0.5.4-dev-20210204-37b2e5247195c3f892ba503d112b74f3d75a7631中验证，已经修复。
