### ISSUE TITLE
S4 - jt_getTransactionByHash：错误的full参数名称建议返回错误提示信息

### ISSUE THREAD

**Issue by zyd82** [caivega/ipfslib#182]
测试版本：v0.5.4-dev-20210207-db1bf99761871c1bbe1b67e2bd6286eba58177fc
用例编号：FCJT_getTransactionByHash_000070

正确的hash参数，但是full参数名称写成"fuuulll"，仍然能够返回不带meta数据的交易信息。此处建议返回相应的提示信息，比如：bad parameter: fuuulll。
```
{
    "jsonrpc": "2.0",
    "method": "jt_getTransactionByHash",
    "params": [
        {
            "hash": "22FBFC64A76AE63EF781ABF42F0269BA3C119D9EE2171E95DAD1F562A37E5777",
            "fuuulll": true
        }
    ],
    "id": 1
}
```
jt_getTransactionByIndex、jt_getTransactionByBlockHashAndIndex、jt_getTransactionByBlockNumberAndIndex也有同样的问题。

**Comment by caivega** [comment]
除了之前已经加了非法参数检查，这次把其他的rpc也一起加上

**Comment by caivega** [comment]
所有的rpc都已经加上非法参数检查，已经修复，下一个build验证

**Comment by zyd82** [comment]
v0.6.4-dev-20210219-ae3070493c2d87812731c2583fe3820089246ee7版本上验证通过。
