### ISSUE TITLE
S4 - 部分接口比如jt_getBlockByNumber，jt_getBalance，出错后的info表述不清晰。

### ISSUE THREAD

**Issue by foreso-GitHub** [caivega/ipfslib#189]
部分接口比如jt_getBlockByNumber，jt_getBalance，出错后的info表述不清晰。以前的版本没有这个问题。
具体如下：
|接口|正确的info|目前错误的info|
|----------------|----------------|----------------|
|jt_getBlockByNumber|'can\'t find block 99900000'|'can\'t find 99900000'|
|jt_getBalance|'can\'t find account j4tBKPidB9iEJMqdatq7rbh14nPhAbCyfg-SWT|'can\'t find j4tBKPidB9iEJMqdatq7rbh14nPhAbCyfg-SWT'|
|jt_getCurrency|'can\'t find currency NoCoin_1'|'can\'t find NoCoin_1'|
|jt_getTransactionReceipt|'can\'t find transaction B9A45BD943EE1F3AB8F505A61F6EE38F251DA723ECA084CBCDAB5076C60F84E8'|'can\'t find B9A45BD943EE1F3AB8F505A61F6EE38F251DA723ECA084CBCDAB5076C60F84E8'|
|jt_getTransactionByHash|'can\'t find transaction B9A45BD943EE1F3AB8F505A61F6EE38F251DA723ECA084CBCDAB5076C60F84E8'|'can\'t find B9A45BD943EE1F3AB8F505A61F6EE38F251DA723ECA084CBCDAB5076C60F84E8'|
|jt_getTransactionByIndex|'can\'t find transaction B9A45BD943EE1F3AB8F505A61F6EE38F251DA723ECA084CBCDAB5076C60F84E8'|'can\'t find B9A45BD943EE1F3AB8F505A61F6EE38F251DA723ECA084CBCDAB5076C60F84E8'|
|jt_getTransactionByBlockHashAndIndex|'can\'t find block 99900000'|'can\'t find 99900000'|
|jt_getTransactionByBlockNumberAndIndex|'can\'t find block 99900000'|'can\'t find 99900000'|
|jt_getBlockTransactionCountByHash|'can\'t find block 99900000'|'can\'t find 99900000'|
|jt_getBlockTransactionCountByNumber|'can\'t find block 99900000'|'can\'t find 99900000'|

版本：v0.6.4-dev-20210218-f79a420c94324f0e122b265a2e7be26573c78249
TestCase：FCJT_getBlockByNumber_000040等

```
{
    "jsonrpc": "2.0",
    "method": "jt_getBalance",
    "params": [
        {
            "address": "j9HeSMn2MwQeP9Xxp6etEZ6uHXwZizbo4a",
            "currency": "6017a934",
            "issuer": "jjjjjjjjjjjjjjjjjjjjjhoLvTp"
        }
    ],
    "id": 1
}

{
    "error": {
        "count": 1,
        "desc": "The compound error.",
        "info": "1 errors"
    },
    "id": 1,
    "jsonrpc": "2.0",
    "result": [
        {
            "error": {
                "desc": "The source account does not exist.",
                "info": "can't find j9HeSMn2MwQeP9Xxp6etEZ6uHXwZizbo4a-6017a934"
            },
            "status": -96,
            "type": "terNO_ACCOUNT"
        }
    ],
    "status": 1000,
    "type": "tedCOMPOUND"
}

```

**Comment by caivega** [comment]
已经修复，下一个build验证

**Comment by foreso-GitHub** [comment]
在版本v0.6.4-dev-20210219-296452520315a8b88ae584f9dbaf97df72b56c7e中验证，已经修复。
