### ISSUE TITLE
S4 - jt_sendTransaction的参数，value必须是string，但fee却必须是number，应该统一类型

### ISSUE THREAD

**Issue by foreso-GitHub** [caivega/ipfslib#27]
jt_sendTransaction的参数，value必须是string，但fee却必须是number，不统一。这两个参数类型应该一致。

1、如果fee不是number，交易请求如下：
{"jsonrpc":"2.0","id":1,"method":"jt_sendTransaction","params":[{"from":"j3C3LAfQ6aTgnG3gvPPEaUE3g6cPnXZQdd","secret":"ss6iFshVyH7zZL2pGiQ4otrrd5uCg","to":"jjsbo9Yz5RTrKAWSWgNtEHdrviMtWYoqZ5","value":"1","fee":"35"}]}

返回错误：
{ id: 0,
  jsonrpc: '2.0',
  result: 'interface conversion: interface {} is string, not float64',
  status: 'error' }

2、如果value不是string，交易请求如下：
{"jsonrpc":"2.0","id":1,"method":"jt_sendTransaction","params":[{"from":"j3C3LAfQ6aTgnG3gvPPEaUE3g6cPnXZQdd","secret":"ss6iFshVyH7zZL2pGiQ4otrrd5uCg","to":"jjsbo9Yz5RTrKAWSWgNtEHdrviMtWYoqZ5","value":1,"fee":12}]}

返回同样的错误：
{ id: 0,
  jsonrpc: '2.0',
  result: 'interface conversion: interface {} is float64, not string',
  status: 'error' }

**Comment by caivega** [comment]
fee 与 value 现在一样，都统一成 string 类型的了，测试环境已更新
