### ISSUE TITLE
S4 - jt_signTransaction：value参数为"1000/swt" 或者 "1000/SWT"时的问题

### ISSUE THREAD

**Issue by zyd82** [caivega/ipfslib#44]
发送如下jt_signTransaction请求，value参数为"1000/swt" 或者 "1000/SWT"
`{
    "jsonrpc": "2.0",
    "method": "jt_signTransaction",
    "params": [
        {
            "from": "j3C3LAfQ6aTgnG3gvPPEaUE3g6cPnXZQdd",
            "secret": "ss6iFshVyH7zZL2pGiQ4otrrd5uCg",
            "to": "jDjvM2rrjgAsYEeFJsSvuXxkbYxZQpdEwu",
            "value": "1000/swt"
        }
    ],
    "id": 1
}`

9545上，返回长串哈希，用jt_sendRawTransaction发起哈希交易，返回如下：
`{
    "id": 1,
    "jsonrpc": "2.0",
    "message": "failed to submit transaction blob 1200002280000000240000000361400000003b9aca0068400000000000000a732102d9e3b2d4ed2a49c1bb3891a62dc275c0c610d7570a37ea174db39ef732aa4ee77446304402200ef560a2f933945b15fce069514ea2b5dd1cee3669a613794a0567e78adc2029022031f2e5d0d2d295888566399b085513325f9f2e92c9904944af23aa636dd7900e811453fed1357fc5d9056891530f5c5957cc31589c59831483ce0c3c63384e9d839ccbf39eb799aece1cf7d1: temUNKNOWN The transactions requires logic not implemented yet.",
    "result": [
        ""
    ],
    "status": "error"
}`

7545上，返回长串哈希，用jt_sendRawTransaction发起哈希交易，返回如下：
`{
    "id": 1,
    "jsonrpc": "2.0",
    "result": [
        ""
    ],
    "status": "success"
}`

根据文档，value是支持"1000/swt" 或者 "1000/SWT"这种写法的，因此这里需要支持这种写法的交易，或者文档里删除对"1000/swt" 或者 "1000/SWT"的支持

**Comment by zyd82** [comment]
9545: 在v0.5.2-dev版本上，支持"1000/SWT"这种写法，但是不支持"1000/swt"这种写法，返回如下：
```
{
    "id": 1,
    "jsonrpc": "2.0",
    "message": {
        "reason": "1 errors",
        "result": [
            {
                "error": "value must be integer type and >= 0",
                "message": {
                    "from": "jGQ14U9BeHn6kV9eofnVsshSCxAecBawPM",
                    "to": "jPdx7mG595P6CowtGYbxRkik9HdWUWtB2J",
                    "value": "0.1/swt"
                },
                "status": -278
            }
        ]
    },
    "result": [
        ""
    ],
    "status": -278
}
```

**Comment by foreso-GitHub** [comment]
补充一下，最好Swt也支持。

**Comment by caivega** [comment]
保证唯一底层币的大写的唯一，代币不得有与底层一样或者转成大写以后一样的symbol

**Comment by zyd82** [comment]
既然底层币SWT必须是大写唯一的，那么"1000/swt"这种写法就不应该支持，返回相应的提示信息就行；另外目前文档里已经没有"1000/swt"这种写法了。

**Comment by caivega** [comment]
目前版本是非大写的底层币，将会报TerNO_CURRENCY的错误，当然因为之前报的问题，现在这种也是发行不出来的

现在还有一个兼顾到用户的方案，就是在rpc验证的时候，把swt及Swt这种非大写的底层币转成大写，方便用户使用（个人意见是没必要，因为rpc的使用者是程序员，而非普通用户，这点的基本要求还是可以接受的，而且也与我们的大原则，不冲突底层币的symbol相符合)，在共识层面的验证中，只验证大写的底层币，非大写的按现在版本处理

**Comment by zyd82** [comment]
验证通过，版本：v0.5.3-dev-20201216-be83b3f3cf9773881eb5fcf277e9b9afe8caaa8c

目前用jt_sendTransaction发送交易时，如果value是"1/swt"或者"1/sWt"等，都能够返回terNO_CURRENCY的错误。

用jt_signTransaction发送交易时，如果value是"1/swt"或者"1/sWt"等，用jt_sendRawTransaction发送返回的签名交易，返回的是terNO_CURRENCY错误。

```
{
    "error": "1 errors",
    "id": 1,
    "jsonrpc": "2.0",
    "result": [
        {
            "error": "failed to submit transaction 1BB757DC3A41D2C9623263D422D9C33C9F1F80E22A4DA586AD0C6BD1BEF39DCB",
            "message": {
                "engine_result": "terNO_CURRENCY",
                "engine_result_code": -87,
                "engine_result_message": "The currency does not exist.",
                "tx_blob": "1200002280000000240000003261d4c44364c5bb00000000000000000000000000735774000000000000000000000000000000000000000000000000000068400000000000000a7321034153eebb406b3593aa7f31a4908e56ed820031db87f4f2e868fb8e1686d5e1e374473045022100c1ccbfe4a06612c2f7b80f94af9191e69a0abf078f4c6761116a312d81e08880022022ae9e3d888ba02941caf8e1b8d1710d60fdb01ad74c36a37b4ba047d2fc0c228114f8500d9a44fce19e8d873b0661a2be53557bb43c831417548b963584f5337addf78dbf78f188682a6ffe",
                "tx_json": {
                    "TransactionType": "Payment",
                    "Flags": 2147483648,
                    "Account": "jPdx7mG595P6CowtGYbxRkik9HdWUWtB2J",
                    "Sequence": 50,
                    "Fee": "10",
                    "SigningPubKey": "034153EEBB406B3593AA7F31A4908E56ED820031DB87F4F2E868FB8E1686D5E1E3",
                    "TxnSignature": "3045022100C1CCBFE4A06612C2F7B80F94AF9191E69A0ABF078F4C6761116A312D81E08880022022AE9E3D888BA02941CAF8E1B8D1710D60FDB01AD74C36A37B4BA047D2FC0C22",
                    "hash": "1BB757DC3A41D2C9623263D422D9C33C9F1F80E22A4DA586AD0C6BD1BEF39DCB",
                    "Destination": "js3MF5kQkTG6NBVj9HEiw9cFe4ckNvMYGg",
                    "Amount": {
                        "value": "12",
                        "currency": "sWt",
                        "issuer": "jjjjjjjjjjjjjjjjjjjjjhoLvTp"
                    }
                }
            },
            "status": -278,
            "type": "temINVALID"
        }
    ],
    "status": -278,
    "type": "temINVALID"
}
```
