### ISSUE TITLE
S1 - jt_getAccount：有时取到的sequence不正确

### ISSUE THREAD

**Issue by foreso-GitHub** [caivega/ipfslib#56]
地址j3C3LAfQ6aTgnG3gvPPEaUE3g6cPnXZQdd，交易的sequence已经发到38并且成功了，但jt_getAccount查，sequence还是只有36。

交易hash：670B4B98C22A508B4BB0667E2A75B24C57989ECDC1DC97CEC04243869AAA88C3，sequence是38。

jt_getAccount返回如下，sequence只有36：
{
    "id": 1,
    "jsonrpc": "2.0",
    "result": {
        "Account": "j3C3LAfQ6aTgnG3gvPPEaUE3g6cPnXZQdd",
        "Balance": "1080002506703",
        "Hash": "0000000000000000000000000000000000000000000000000000000000000000",
        "LedgerEntryType": "AccountRoot",
        "Sequence": 36
    },
    "status": "success"
}

**Comment by caivega** [comment]
查了一下，发现是因为from与to的帐户一样导致的，已经修复，现在from与to帐户一样，依然可以转帐

**Comment by foreso-GitHub** [comment]
好的，后面再跑一段时间，如果没有再遇到这个问题，就关闭。

**Comment by foreso-GitHub** [comment]
20201105版本上已经修正。
